services:
    truecode:
            container_name: truecode
            build:
                context: .
                dockerfile: Dockerfile
            ports:
                - '5010:80'
            environment:
                - ASPNETCORE_URLS=http://+:80
                - ASPNETCORE_ENVIRONMENT=Development
